// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMIoIuzZHwGcrbylDwnWG3BCiDB0atScA',
    appId: '1:1011423375380:ios:7f276f6fa025bbfe46b701',
    messagingSenderId: '1011423375380',
    projectId: 'medi-remind-738cc',
    storageBucket: 'medi-remind-738cc.firebasestorage.app',
    iosBundleId: 'com.example.mediRemind',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMIoIuzZHwGcrbylDwnWG3BCiDB0atScA',
    appId: '1:1011423375380:ios:7f276f6fa025bbfe46b701',
    messagingSenderId: '1011423375380',
    projectId: 'medi-remind-738cc',
    storageBucket: 'medi-remind-738cc.firebasestorage.app',
    iosBundleId: 'com.example.mediRemind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1RkQG6sV_VTz27hgPPXrvx4bqYQQMUfA',
    appId: '1:1011423375380:web:d16a96d6452ebea646b701',
    messagingSenderId: '1011423375380',
    projectId: 'medi-remind-738cc',
    authDomain: 'medi-remind-738cc.firebaseapp.com',
    storageBucket: 'medi-remind-738cc.firebasestorage.app',
    measurementId: 'G-VRDYHNZ8LZ',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1RkQG6sV_VTz27hgPPXrvx4bqYQQMUfA',
    appId: '1:1011423375380:web:d16a96d6452ebea646b701',
    messagingSenderId: '1011423375380',
    projectId: 'medi-remind-738cc',
    authDomain: 'medi-remind-738cc.firebaseapp.com',
    storageBucket: 'medi-remind-738cc.firebasestorage.app',
    measurementId: 'G-VRDYHNZ8LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOVwNXuKzzxpTplrKTduE5GDD1PcWIFA',
    appId: '1:1011423375380:android:dfe44edd2d9bdf8746b701',
    messagingSenderId: '1011423375380',
    projectId: 'medi-remind-738cc',
    storageBucket: 'medi-remind-738cc.firebasestorage.app',
  );
}
